name: Build, and publish spec to GitHub Pages and /TR/

on: workflow_dispatch

jobs:
  main:
    name: Build, Validate and Deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: w3c/spec-prod@v2
        with:
          TOOLCHAIN: respec
          SOURCE: index.html
          DESTINATION: index.html
          W3C_ECHIDNA_TOKEN: ${{ secrets.W3C_TR_TOKEN }}
          W3C_WG_DECISION_URL: https://lists.w3.org/Archives/XXX
          W3C_BUILD_OVERRIDE: |
            status: DNOTE

# not set 'warning' to BUILD_FAIL_ON (not to cause error by bikeshed warning?)

